### ISSUE TITLE
Add an option to skip paths (e.g. node_modules)

### ISSUE THREAD

**Issue by drewbrew** [browniebroke/django-codemod#264]
**Is your feature request related to a problem? Please describe.**
I use [django-tailwind](https://github.com/timonweb/django-tailwind) for CSS in a project.  One of the JS libraries it imports has some Python 2 code that it puts inside my `theme/static_src/node_modules/` directory, which is already in my `.gitignore`. Because my project is using Python 3.8, the code modder throws syntax errors for those 23 files (which is technically correct).

**Describe the solution you'd like**
I'd like the ability to exclude paths (via a command-line switch or other means) or have the option to have `django-codemod` skip files ignored by git.

**Additional context**
N/A, but this tool is excellent!

**Comment by browniebroke** [comment]
Yes, sounds like a reasonable to add an exclude option. I think this option should be repeatable (to allow excluding multiple paths).

Pull request welcome.

**Comment by browniebroke** [comment]
Implementation note: we currently use [the `gather_files` function](https://github.com/Instagram/LibCST/blob/753a4f575ef238ce957bf192628f64d8d015ca58/libcst/codemod/_cli.py#L77-L96) from libCST to get the list of files to codemod. 

We might want to copy that function in django-codemod and change it to support exclusion. In terms of how it's exposed to the user, we could take [the `--exclude` option from black](https://black.readthedocs.io/en/stable/installation_and_usage.html#command-line-options) as inspiration, with a list of sensible defaults (the same ones?).

**Comment by browniebroke** [comment]
Digging through black source code, I realised that it parses `.gitignore` file and ignores anything matching it. It seems like it would solve your problem as well as similar ones with virtualenv (#278)...

**Comment by browniebroke** [comment]
I just published version 1.1.0 which should now honor the content of `.gitignore`. Does it solve your problem?

**Comment by drewbrew** [comment]
@browniebroke This should be perfect. Thank you!

I'll download and try it out just to make sure.

**Comment by drewbrew** [comment]
Confirmed, it works wonderfully.

One thing to note: it only seems to parse the top-level `.gitignore`; if a subdirectory has its own version, git respects that but this tool does not.

**Comment by browniebroke** [comment]
Yes that seems about right. It just parsing one from the repo root. Do you have many gitignore? Wondering if we could just document it or if we should try to handle it...

**Comment by drewbrew** [comment]
I think document it and be done. It's a rare pattern that shouldn't really exist outside of using submodules in my opinion.
