### ISSUE TITLE
Recommended command recurses into my virtualenv

### ISSUE THREAD

**Issue by adamchainz** [browniebroke/django-codemod#278]
**Is your feature request related to a problem? Please describe.**
I ran the recommended command in usage, `djcodemod run --deprecated-in 3.0 .` . I wondered how there were 10k files to modify before realizing it's recursing into my virtualenv and rewriting everything there.

**Describe the solution you'd like**
A minimal solution would be to say not recommend `.` as the path.

A more complete solution would be to check if a folder looks like a virtualenv (e.g. has a "bin/activate") before recursing into it.

**Additional context**
n/a

**Comment by browniebroke** [comment]
Right... I agree that -at least- the documentation should be updated to not recomment `.`. I'm not sure about guessing exclusion rules, though. 

Someone also mentioned an option to exclude some folders #264 which could default to a list of common things which should be excluded. The `--exclude` option from black would probably be a good starting point.
