### ISSUE TITLE
Add tests to sdist

### ISSUE THREAD

**Issue by jayvdb** [browniebroke/django-codemod#654]
**Describe the feature**
Currently the tests are not included in the PyPI sdist.  As a result in order to do packaging for openSUSE at https://build.opensuse.org/package/show/devel:languages:python:django/python-django-codemod , I need to fetch the sdist from Github, which is a few extra steps.

Please can the tests be added to the sdist.

**To Reproduce**
Download sdist from PyPI, untar and see that now tests are present.

**Comment by browniebroke** [comment]
Tests are not included intentionally. I don't see much point in them as the end users don't really need them to run the code, it's just adding some extra bytes to download from PyPI, using extra bandwidth and storage.

Pardon my ignorance, but I don't understand why this needs to be packaged on openSUSE, don't people have pip/pipx installed/installable there?

**Comment by jayvdb** [comment]
Regarding why, I am a maintainer of the django package collection on openSUSE, and I frequently use codemod to fixup packages which havent done a release of the compatibility needed for the latest release of Django.

e.g. https://build.opensuse.org/package/show/devel:languages:python:django/python-django-user-agents
https://build.opensuse.org/package/view_file/devel:languages:python:django/python-django-user-agents/python-django-user-agents.spec?expand=1 is where you can see the tool being used.  Packages get deleted on openSUSE if they fail to build for six weeks, so the clock is ticking.  As soon as another Django release occurs, approx 20 django packages break.  Your tool means I don't need to disable newly failing tests, or apply lots of patches against the most recent released version of a package, etc. Much appreciated.

https://pypi.org/project/django-codemod/#files shows that there are wheels and sdists being uploaded.  The wheels do not include tests, and are intended for normal pip usage.  The wheels are downloaded by default by pip, and include only what is necessary to run the code.  The sdist (source distribution) is where the tests reside, and are only fetched explicitly via pip arguments, or by URL directly as my package maintenance scripts do.

**Comment by browniebroke** [comment]
This took longer because the build was broken due to an unrelated issue: it looks like something wonky was going on in the cache and it's not speeding the build very much so I removed it #658.

Thanks for the contribution, not a big fan of shipping tests to PyPI, but as you explained, it shouldn't be too bad since it's only in the source distribution, so I'm good with this 👍🏻
